[workspace]

members = [
    "branches",
    "exercices_ch3",
    "functions",
    "guessing_game",
    "kata",
    "loops",
    "ownership",
    "slices",
    "structure",
    "variables",
    "rectangles",
    "enums"
]